name: Promote Artifact 🚦

on:
  workflow_dispatch:

jobs:
  promote-dev:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    environment: dev
    steps:
      - name: Get Tag Name
        id: get_tag_name
        run: |
          TAG_NAME=${{ github.ref }}
          TAG_NAME=${TAG_NAME#refs/tags/}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Promote to Develoment
        run: |
          echo "Creating PR to promote to Development"
          echo "Updating image tag  ${{ env.TAG_NAME }} in dev environment repository"

  promote-qa:
    runs-on: ubuntu-latest
    needs: promote-dev
    environment: dev
    steps:
      - name: Promote to QA
        run: |
          echo "Creating PR to promote to QA"
          echo "Updating image tag  ${{ env.TAG_NAME }} in QA environment repository"

  promote-stg:
    runs-on: ubuntu-latest
    needs: promote-qa
    environment: dev
    steps:
      - name: Promote to Staging
        run: |
          echo "Creating PR to promote to Staging"
          echo "Updating image tag  ${{ env.TAG_NAME }} in Staging environment repository"

  promote-pro:
    runs-on: ubuntu-latest
    needs: promote-stg
    environment: dev
    steps:
      - name: Promote to Production
        run: |
          echo "Creating PR to promote to Production"
          echo "Updating image tag  ${{ env.TAG_NAME }} in Production environment repository"
