name: Promote Artifact 🚦

on:
  workflow_dispatch:
    inputs:
      release:
        description: Release to promote (e.g. v1.0.0)
        required: true
        type: string

jobs:
  promote-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Promote to Develoment
        run: |
          echo "Creating PR to promote to Development"
          echo "Updating image tag  ${{ inputs.release }} in dev environment repository"

  promote-qa:
    runs-on: ubuntu-latest
    needs: promote-dev
    environment: dev
    steps:
      - name: Promote to QA
        run: |
          echo "Creating PR to promote to QA"
          echo "Updating image tag  ${{ inputs.release }} in QA environment repository"

  promote-stg:
    runs-on: ubuntu-latest
    needs: promote-qa
    environment: dev
    steps:
      - name: Promote to Staging
        run: |
          echo "Creating PR to promote to Staging"
          echo "Updating image tag  ${{ inputs.release }} in Staging environment repository"

  promote-pro:
    runs-on: ubuntu-latest
    needs: promote-stg
    environment: dev
    steps:
      - name: Promote to Production
        run: |
          echo "Creating PR to promote to Production"
          echo "Updating image tag  ${{ inputs.release }} in Production environment repository"
